name: Build ESPectrum Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite la ejecución manual del workflow

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [psram, nopsram]  # Los entornos definidos en platformio.ini

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build ESPectrum firmware
      run: platformio run -e ${{ matrix.env }}  # Usando los entornos correctos

    - name: Upload ESPectrum firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ESPectrum-firmware-${{ matrix.env }}
        path: |
          .pio/build/${{ matrix.env }}/*.bin
          .pio/build/${{ matrix.env }}/*.elf

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Notify on Failure
      run: echo "Build failed for ESPectrum environment ${{ matrix.env }}"  # Ajusta la acción de notificación según lo necesites
